stages:
  - test

image:                             ${REGISTRY}/bridge-ci-linux:latest

variables:
  GIT_STRATEGY:                    fetch
  GIT_SUBMODULE_STRATEGY:          recursive
  CI_SERVER_NAME:                  "GitLab CI"
  REGISTRY:                        registry.parity.io/parity/infrastructure/scripts

.check-bridge:                     &check-bridge
  stage: test
  before_script:
    - rustup show
    - cargo --version
    - parity --version
    - solc --version
  script:
    - rustup default ${RUST_DEFAULT}
    - cargo fmt --verbose --all -- --check
    - time cargo test --verbose -all --color=always -- --nocapture
    - sccache --show-stats
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  tags:
    - linux-docker

check-stable:
  variables:
    RUST_DEFAULT:                  stable
  <<:                              *check-bridge

check-beta:
  variables:
    RUST_DEFAULT:                  beta
  <<:                              *check-bridge

check-nightly:
  variables:
    RUST_DEFAULT:                  nightly
  <<:                              *check-bridge
