branches:
  only:
  - master

matrix:
  include:
    - language: rust
      rust: stable-2018-05-29
      sudo: required
      dist: trusty
      cache: cargo
      fast_finish: false
      install:
        - sudo apt-get --yes install snapd
        - sudo snap install parity --stable
        - sudo snap install solc --stable
        - snap list
      before_script:
        - export PATH=/snap/bin:${PATH}
        - rustup component add rustfmt-preview
        - rustfmt --version
      script:
        # using --write-mode=diff instructs rustfmt to exit with an error code if the input is not formatted correctly
        - cargo fmt --all -- --write-mode=diff
        - env BACKTRACE=1 cargo test --all -- --nocapture
    - language: rust
      rust: beta
      sudo: required
      dist: trusty
      cache: cargo
      fast_finish: false
      install:
        - sudo apt-get --yes install snapd
        - sudo snap install parity --stable
        - sudo snap install solc --stable
        - snap list
      before_script:
        - export PATH=/snap/bin:${PATH}
      script:
        - env BACKTRACE=1 cargo test --all -- --nocapture
    - language: rust
      rust: nightly
      sudo: required
      dist: trusty
      cache: cargo
      fast_finish: false
      install:
        - sudo apt-get --yes install snapd
        - sudo snap install parity --stable
        - sudo snap install solc --stable
        - snap list
      before_script:
        - export PATH=/snap/bin:${PATH}
      script:
        - env BACKTRACE=1 cargo test --all -- --nocapture
    - language: node_js
      node_js: "9.11.1"
      sudo: false
      cache: yarn
      before_script:
        - cd truffle
        - yarn install
      script:
        - yarn run ci
      after_script:
        - cat coverage/lcov.info | yarn run coveralls

env:
  global:
  - secure: zdEco0QAPik4peDfWuLHHex67LVe3E7c5VJNx+7ygH1pt+mzgobKo8jgT7WuH70xPRA717txNaj/zYGj5EuBKLn+Tkw3feDjrISYRD7ZOXFm1urv53KDx8xh2QJld2fHOc4UWcQ1qqBOWWOR9donuOaRfdDSOpWjLhl14heMgsW3o5Q/V4HN//VPHQctzaCq6r5eerx82B6SSNQ7+42rESu37N0Plv8JtCswihCuoUsMuzbXGwGzafR8IVf5WJPB1WM1KpjdWHgZCCgIfdH6C9fJ1P4fd2Z7EQJ0PYwxRntPlONzUr5khGPldXn7Czwoq9Go4eOZaTwHizprI/KCXBXASXQ/Z7EsU2AKl90qvUHLDB9i4aa/eDrkzQGPQ+dkjNckdQaaucIKX/r8VDm7ZVefkLOgbzc1plE6/TXslAS/n0OoXUXydzueyqi8oeVEagt/nSYaR4t/8C10eC/6gjVF6X6mpgM6/p8eVrN8bltMa0KSDfRvhi3kU1Nmc5b3CWg+neWYYFPHak3GyFwh3uRC0LJroO+j+dkQZiEpSsMgthx69RBDjYvoi3T5FGwt5s/FfnOtcHM65M9sGubMW4DsVaI7OHt7FUnp5dlqxk6NGT68R/E1ZeCwr7Y4QCXr4agew5OpxTni4MK7aCVnmAtabNVLI4wKdCy2ULJWLsE=
