[parity]
chain = "examples/parity_spec.json"

[account]
unlock = ["0x006e27b6a72e1f34c626762f3c4761547aff1421"]
password = ["examples/parity_password"]

[mining]
engine_signer = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
