[package]
name = "bridge"
version = "0.4.0"
authors = ["debris <marek.kotewicz@gmail.com>", "snd <kruemaxi@gmail.com>"]

[dependencies]
bridge-contracts = { path = "../contracts" }
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1.8"
tokio-timer = "0.1.2"
toml = "0.4.2"
web3 = { git = "https://github.com/tomusdrw/rust-web3", branch = "bridge" }
error-chain = "0.11.0-rc.2"
ethabi = "5.1"
rustc-hex = "1.0"
log = "0.3"
ethereum-types = "0.2"
pretty_assertions = "0.2.1"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.6.1"
